module(
    name = "score_openssl",
    version = "3.6.1",
)

# Standard Bazel dependencies required to compile C++ via configure/make
bazel_dep(name = "rules_cc", version = "0.2.17")
bazel_dep(name = "rules_foreign_cc", version = "0.15.1")
bazel_dep(name = "platforms", version = "1.1.0")
bazel_dep(name = "score_bazel_platforms", version = "1.1.0")

# Central C++ toolchains required for cross-compiling to QNX8 target environments
bazel_dep(
    name = "score_bazel_cpp_toolchains",
    version = "1.0.3",
    dev_dependency = True,
)

# HTTP archive rule for downloading OpenSSL source code
http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "openssl_source",
    build_file_content = "filegroup(name = 'all', srcs = glob(['**']), visibility = ['//visibility:public'])",
    patch_args = ["-p1"],
    patches = ["//patches:openssl_qnx_target.patch"],
    sha256 = "b1bfedcd5b289ff22aee87c9d600f515767ebf45f77168cb6d64f231f518a82e",
    strip_prefix = "openssl-3.6.1",
    urls = ["https://www.openssl.org/source/openssl-3.6.1.tar.gz"],
)

# Use preinstalled host tools to prevent bootstrapping pkgconfig under strict C11 flags
register_toolchains(
    "@rules_foreign_cc//toolchains:preinstalled_pkgconfig_toolchain",
)
